In [24]:
import torch

a = torch.Tensor([[0,1,0],[1,0,0], [0,0,0]])
print('a: \n',a)
print('*a.size()\n', *a.size())
print('a.size(1)\n', a.size(1))
b = a.sum(1)
print('b: \n', b)
c = b.unsqueeze(1)
print('c: \n', c)
d = c.expand(3,3)
print('d: \n', d)

#b = torch.eye(a.size(1))
#print(*a.size())
#print(b)
#c = a.unsqueeze(2).expand(*a.size(), a.size(1))
#d = c * b
#print(d)

a: 
 tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]])
*a.size()
 3 3
a.size(1)
 3
b: 
 tensor([1., 1., 0.])
c: 
 tensor([[1.],
        [1.],
        [0.]])
d: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])


In [35]:
import torch

a = torch.Tensor([[0,1,0],[1,0,0], [0,0,0]])
print('a: \n',a)
b = a.sum(1)
print('b: \n',b)
c = torch.diag(b)
print('c: \n',c)

a: 
 tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]])
b: 
 tensor([1., 1., 0.])
c: 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])


In [39]:
import torch

a = torch.Tensor([[0,1,0],[1,0,0], [0,0,0]])
print('a: \n',a)
b = a.sum(1)
print('b: \n',b)
c = b.repeat(3).view(3,3)
print('c: \n',c)
d = torch.diag(c,1)
print('d: \n',d)

a: 
 tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]])
b: 
 tensor([1., 1., 0.])
c: 
 tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]])
d: 
 tensor([1., 0.])


In [44]:
x = torch.eye(3)
print(x)
x = x.reshape((1, 3, 3))
print(x)
y = x.repeat(5, 1, 1)
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])


In [45]:
torch.eye(81).reshape((1,81,81)).repeat(50)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [48]:
torch.eye(81).reshape((1,81,81)).repeat(81,1,1)

tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        ...,

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0., 

In [55]:
torch.ones(50,83,83)

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1., 

In [58]:
import torch

a = torch.Tensor([[0,1,0],[1,0,0], [0,0,0]])
print('a: \n',a)
b = a.sum(1)
print('b: \n', b)
c = b.unsqueeze(1)
print('c: \n', c)

ones = torch.ones(1,3,3)
print('ones: \n', ones)



a: 
 tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]])
b: 
 tensor([1., 1., 0.])
c: 
 tensor([[1.],
        [1.],
        [0.]])
ones: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [80]:
import torch

v = torch.Tensor([[0],[1]])
M = torch.Tensor([[[1, 1, 1]],[[1, 1, 1]]])

result = torch.einsum('bp, bqr->bpqr', v, M)
print(result)

v = torch.Tensor([[[0],[1]],[[1],[1]]])
M = torch.Tensor([[[[1, 1, 1]],[[1, 1, 1]]],[[[1, 1, 1]],[[1, 1, 1]]]])

result = torch.einsum('xbp, xbqr->xbpqr', v, M)
print(result)
print('shape of v: ', v.shape)
print('shape of M: ', M.shape)

tensor([[[[0., 0., 0.]]],


        [[[1., 1., 1.]]]])
tensor([[[[[0., 0., 0.]]],


         [[[1., 1., 1.]]]],



        [[[[1., 1., 1.]]],


         [[[1., 1., 1.]]]]])
shape of v:  torch.Size([2, 2, 1])
shape of M:  torch.Size([2, 2, 1, 3])


In [83]:
v = torch.Tensor([[[0],[1]],[[1],[0]]])
print(v.shape)
M = torch.Tensor([[[6,6,6],[7,7,7]],[[9,9,9],[5,5,5]]])
print(M.shape)
                

torch.Size([2, 2, 1])
torch.Size([2, 2, 3])


In [90]:
import torch

#2, 2, 1
#2, 2, 3

v = torch.Tensor([[[0],[1]],[[1],[0]]])
M = torch.Tensor([[[6,6,6],[7,7,7]],[[9,9,9],[5,5,5]]])

result = torch.einsum('bxs,bxy -> bxy', v, M)
print(result)

print('shape of v: ', v.shape)
print('shape of M: ', M.shape)

tensor([[[0., 0., 0.],
         [7., 7., 7.]],

        [[9., 9., 9.],
         [0., 0., 0.]]])
shape of v:  torch.Size([2, 2, 1])
shape of M:  torch.Size([2, 2, 3])


In [28]:
import torch

#2, 2, 1
#2, 2, 3

v = torch.Tensor([[1,1,0,0,1,0],[0,0,1,1,0,0]])
m = torch.diag_embed(v)

print('shape of v: ', v.shape)
print('shape of m: ', m.shape)

print('result:')

result = torch.einsum('bs,by -> bsy', v, v) - m
print(result)

#result =  torch.tensordot(v, v, 0) - m
#print(result)



shape of v:  torch.Size([2, 6])
shape of m:  torch.Size([2, 6, 6])
result:
tensor([[[[1., 1., 0., 0., 1., 0.],
          [0., 0., 1., 1., 0., 0.]],

         [[1., 1., 0., 0., 1., 0.],
          [0., 0., 1., 1., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[1., 1., 0., 0., 1., 0.],
          [0., 0., 1., 1., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[1., 1., 0., 0., 1., 0.],
          [0., 0., 1., 1., 0., 0.]],

         [[1., 1., 0., 0., 1., 0.],
          [0., 0., 1., 1., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]])
