In [18]:
import torch

x = torch.Tensor(2, 3)    # Create an un-initialized Tensor of size 2x3
print(x)                  # Print out the Tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
w = torch.rand(2, 3)    # Initialize with random values



In [29]:
w[0,:] = 0

In [30]:
w

tensor([[0.0000, 0.0000, 0.0000],
        [0.5926, 0.6860, 0.1673]])

In [31]:
a = np.array([1, 2, 3])
v = torch.from_numpy(a) 

In [32]:
a

array([1, 2, 3])

In [33]:
v

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
b = v.numpy()

In [35]:
b

array([1, 2, 3])

In [36]:
b[1] = -1 

In [37]:
assert(a[1] == b[1])  

In [38]:
a

array([ 1, -1,  3])

In [39]:
x = torch.randn(2, 3) 

In [40]:
x

tensor([[ 2.7148, -0.7938,  0.3992],
        [ 0.5449, -0.5913, -2.2864]])

In [41]:
y = x.view(6) 

In [42]:
y

tensor([ 2.7148, -0.7938,  0.3992,  0.5449, -0.5913, -2.2864])

In [43]:
eye = torch.eye(3) 

In [44]:
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [45]:
v = torch.ones(10)
v

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
v = torch.ones(2, 1, 2, 1) 
v

tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])

In [47]:
v = torch.ones_like(eye) 
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
v = torch.ones(3, 3)
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
v[1].fill_(2)
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]])

In [50]:
v[2].fill_(3)
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [51]:
v = torch.arange(5)
v

tensor([0, 1, 2, 3, 4])

In [52]:
v = torch.arange(0, 5, step=1) 
v

tensor([0, 1, 2, 3, 4])

In [53]:
v = torch.arange(9)

In [54]:
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
v = v.view(3, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [56]:
v = torch.linspace(1, 10, steps=10)
v

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
v = torch.logspace(start=-10, end=10, steps=5)
v

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [58]:
c = torch.ByteTensor([0, 1, 1, 0])
c

tensor([0, 1, 1, 0], dtype=torch.uint8)

In [59]:
indices = torch.LongTensor([0, 2])

In [60]:
indices

tensor([0, 2])